### ISSUE TITLE
specifying db connection

### ISSUE THREAD

**Issue by rutchkiwi** [derhuerst/pev2-cli#1]
Hi, cool tool!

Is there any way to say which DB connection to use? For example I want to test against my production environment specified in a string like postgres://.....

**Comment by derhuerst** [comment]
Because `pev2-cli` uses the `psql` CLI tool provided by PostgreSQL, you can use [all environment variables that it supports](https://www.postgresql.org/docs/current/libpq-envars.html).

**Comment by rutchkiwi** [comment]
ah thanks! Kinda but seems like psql does not have an env variable for a [Connection URI](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)? Like `postgresql://localhost/web`

**Comment by derhuerst** [comment]
Yeah, looks like it doesn't support them.

For this project though, I see them as out-of-scope; I already hesitated letting `pev2-cli` spawn `psql`: I don't really consider *executing* the query to be `pev2-cli`'s job, it should rather just take care of *visualizing* the result; But because the flow (`psql -f query.sql | pev2`) felt a bit too complicated.

Instead, I encourage you to

- either use the individual `PG*` env vars (AFAIK they're supported by every well-known PostgreSQL client lib),
- or propose that libpq/`psql` adopts a URI-based env var.

**Comment by rutchkiwi** [comment]
Thanks!! I'll probably stick with just copy pasting for now. Cheers again
